# Generated by Django 5.1.3 on 2026-03-06 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssignEaseApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('coding', 'Coding'), ('non_coding', 'Non-Coding'), ('database', 'Database')], default='coding', max_length=20),
        ),
        migrations.CreateModel(
            name='DatabaseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('expected_query', models.TextField(blank=True, help_text="Teacher's solution query")),
                ('expected_result', models.JSONField(help_text='Expected query result as JSON')),
                ('total_marks', models.FloatField(default=10.0)),
                ('order', models.IntegerField(default=0)),
                ('hints', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_questions', to='AssignEaseApp.assignment')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('sqlite', 'SQLite')], default='sqlite', max_length=20)),
                ('schema_sql', models.TextField(help_text='CREATE TABLE statements')),
                ('sample_data_sql', models.TextField(blank=True, help_text='INSERT statements for sample data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='database_schema', to='AssignEaseApp.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_query', models.TextField()),
                ('query_result', models.JSONField(blank=True, help_text='Actual query result', null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('execution_time', models.FloatField(blank=True, help_text='Query execution time in ms', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('auto_marks', models.FloatField(default=0.0)),
                ('custom_marks', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('checked', 'Checked'), ('reassigned', 'Reassigned'), ('rejected', 'Rejected')], default='submitted', max_length=50)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_submissions', to='AssignEaseApp.assignment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='AssignEaseApp.databasequestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('student', 'assignment', 'question')},
            },
        ),
    ]
