# Generated by Django 5.1.3 on 2026-03-20 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssignEaseApp', '0003_add_question_type_to_database_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('coding', 'Coding'), ('non_coding', 'Non-Coding'), ('database', 'Database'), ('dynamic', 'Dynamic')], default='coding', max_length=20),
        ),
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(max_length=50)),
                ('starter_code', models.TextField(blank=True, null=True)),
                ('total_marks', models.FloatField(default=10.0)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_questions', to='AssignEaseApp.assignment')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CodingTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(blank=True, default='')),
                ('expected_output', models.TextField(blank=True, default='')),
                ('marks', models.IntegerField(default=1)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('hidden', 'Hidden')], default='hidden', max_length=10)),
                ('timeout', models.IntegerField(default=2)),
                ('memory_limit', models.IntegerField(default=128000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='AssignEaseApp.codingquestion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NonCodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('submission_format', models.CharField(choices=[('text', 'Text Answer'), ('file', 'File Submission')], default='text', max_length=20)),
                ('total_marks', models.FloatField(default=10.0)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_coding_questions', to='AssignEaseApp.assignment')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
